# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


u1 = User.create! :name => 'Tundra Swan', :email => 'q@q.com', :password => 'qqqqqq', :password_confirmation => 'qqqqqq', :admin => true
u2 = User.create! :name => 'Caramel Swan', :email => 'w@w.com', :password => 'wwwwww', :password_confirmation => 'wwwwww'

Article.create!(title: "This is my first project!", description: "So this is the week 3 project where we made a game using HTML, CSS and JavaScript.", bg_image: "http://assets1.bigthink.com/system/idea_thumbnails/60118/size_1024/computer_code.jpg", proj_image: "p_url", git_link: "https://github.com/github/gitignore", difficulty: 3, user_id: u1.id, author: u1.name)
Article.create!(title: "This is my second project!", description: "This is the week 6 project where we made a basic project portfolio application using ruby on rails and web dev languages.", bg_image: "https://previews.123rf.com/images/stockbroker/stockbroker1111/stockbroker111100770/11210810-Businessmen-working-on-computers-Stock-Photo-business-computers-people.jpg", proj_image: "p_url", git_link: "https://github.com/github/gitignore", difficulty: 4, user_id: u1.id, author: u1.name)
Article.create!(title: "This is the week 3 project.", description: "This was the project game where we used web dev languages to build a game that a user or users could play.", bg_image: "http://www.lcca.org.uk/media/114625/business-management.jpg?anchor=center&mode=crop&width=1024&height=520&rnd=131152197410000000", proj_image: "p_url", git_link: "https://github.com/github/gitignore", difficulty: 3, user_id: u2.id, author: u2.name)
Article.create!(title: "This is my first project!", description: "So this is the week 3 project where we made a game using HTML, CSS and JavaScript.", bg_image: "http://www.heyuguys.com/images/2010/12/Tron-Legacy-Fan-Art-Tube-Map.jpg", proj_image: "p_url", git_link: "https://github.com/github/gitignore", difficulty: 3, user_id: u1.id, author: u1.name)
Article.create!(title: "This is my second project!", description: "This is the week 6 project where we made a basic project portfolio application using ruby on rails and web dev languages.", bg_image: "http://assets1.bigthink.com/system/idea_thumbnails/60118/size_1024/computer_code.jpg", proj_image: "p_url", git_link: "https://github.com/github/gitignore", difficulty: 4, user_id: u1.id, author: u1.name)
Article.create!(title: "This is the week 3 project.", description: "This was the project game where we used web dev languages to build a game that a user or users could play.", bg_image: "https://previews.123rf.com/images/stockbroker/stockbroker1111/stockbroker111100770/11210810-Businessmen-working-on-computers-Stock-Photo-business-computers-people.jpg", proj_image: "p_url", git_link: "https://github.com/github/gitignore", difficulty: 3, user_id: u2.id, author: u2.name)
Article.create!(title: "This is my first project!", description: "So this is the week 3 project where we made a game using HTML, CSS and JavaScript.", bg_image: "http://www.uscib.org/uscib-content/uploads/2017/06/competitiveness_business-1024x691.jpg", proj_image: "p_url", git_link: "https://github.com/github/gitignore", difficulty: 3, user_id: u1.id, author: u1.name)
Article.create!(title: "This is my second project!", description: "This is the week 6 project where we made a basic project portfolio application using ruby on rails and web dev languages.", bg_image: "http://assets1.bigthink.com/system/idea_thumbnails/60118/size_1024/computer_code.jpg", proj_image: "p_url", git_link: "https://github.com/github/gitignore", difficulty: 4, user_id: u1.id, author: u1.name)
Article.create!(title: "This is the week 3 project.", description: "This was the project game where we used web dev languages to build a game that a user or users could play.", bg_image: "https://previews.123rf.com/images/stockbroker/stockbroker1111/stockbroker111100770/11210810-Businessmen-working-on-computers-Stock-Photo-business-computers-people.jpg", proj_image: "p_url", git_link: "https://github.com/github/gitignore", difficulty: 3, user_id: u2.id, author: u2.name)
Article.create!(title: "This is my first project!", description: "So this is the week 3 project where we made a game using HTML, CSS and JavaScript.", bg_image: "https://previews.123rf.com/images/stockbroker/stockbroker1111/stockbroker111100770/11210810-Businessmen-working-on-computers-Stock-Photo-business-computers-people.jpg", proj_image: "p_url", git_link: "https://github.com/github/gitignore", difficulty: 3, user_id: u1.id, author: u1.name)
Article.create!(title: "This is my second project!", description: "This is the week 6 project where we made a basic project portfolio application using ruby on rails and web dev languages.", bg_image: "http://www.uscib.org/uscib-content/uploads/2017/06/competitiveness_business-1024x691.jpg", proj_image: "p_url", git_link: "https://github.com/github/gitignore", difficulty: 4, user_id: u1.id, author: u1.name)
Article.create!(title: "This is the week 3 project.", description: "This was the project game where we used web dev languages to build a game that a user or users could play.", bg_image: "http://assets1.bigthink.com/system/idea_thumbnails/60118/size_1024/computer_code.jpg", proj_image: "p_url", git_link: "https://github.com/github/gitignore", difficulty: 3, user_id: u2.id, author: u2.name)